### PR TITLE
Added support for any SPI interface

### PR DESCRIPTION
**Pull request by cfrp-spin**

### CODE REVIEW

**Review by JiriBilek — CHANGES_REQUESTED** [review]
Thanks, looking good. Only please move the optional parameter in WiFiSpiClass::init to the end of the parameter list. We don't want to break existing code.

**Comment by cfrp-spin** [comment]
Changed the initialization list as to not break old code. Also added the yield() function to waitForSlaveTxReady() and waitForSlaveRxReady(), as it was holding the entire sketch for the timeout duration.

**Comment by cfrp-spin** [comment]
I'm having a lot of timeouts on waitForSlaveRxReady, which cause a tcp disconnect. I'm initializing WiFiSpi with 10MHz max speed, setting up a server, opening a client and then requesting the number of bytes available for read every 10ms. Any reason why I should be hitting the 3s timeout?

(should this be moved to an issue?)

**Comment by JiriBilek** [comment]
Please try the development version of this library and if it doesn't help, open a nwe issue. In development branch I tuned SPI timeouts because I saw rejected messages time to time. This happened only on STM32F1, not on ATMega.

**Comment by JiriBilek** [comment]
The changes are ok, thanks. I'll test it and merge ASAP.
J.

**Review by JiriBilek — APPROVED** [review]

**Comment by JiriBilek** [comment]
Reopening to be able to merge :)

**Pull request merged**
